version: '3.7'
services:
  node-latest:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["npm", "run", "start"]
  node-old:
    image: node:14
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["npm", "run","bstart"]
